server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/new_db
    username: postgres
    password: 9890
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  admin:
    username: admin
    password: 9890

cors:
  allowed-origins: "https://jwelery-shop.vercel.app,http://localhost:3000"
